services:

  postgres:
    image: postgres:18
    container_name: ai-task-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ai_task_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  app:
    image: ai-task-api
    container_name: ai-task-api
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      GROQ_API_KEY: ${GROQ_API_KEY}
      GROQ_MODEL: ${GROQ_MODEL}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ai_task_db
    ports:
      - "8080:8080"

volumes:
  postgres_data: